### ISSUE TITLE
Browser build with dependencies

### ISSUE THREAD

**Issue by danielkcz** [BlackDice/scent#19]
Current prebuilt file in a lib folder is not that useful as it doesn't include any dependencies. Ideally we should have a separate bundle with Scent along with bundle of dependencies that can be included if they are not supplied from anywhere else.

Consider using Webpack instead of Browserify as it's much easier to configure.

**Comment by martikaljuve** [comment]
Have you tried [Rollup](https://www.npmjs.com/package/rollup)? It uses tree-shaking to get quite nice minimal bundles. 

I'm using Browserify to create two bundles (`bundle.js` for my local code, `vendor.js` for Scent and other rarely-changing dependencies), it works quite well in my case.

**Comment by danielkcz** [comment]
Haven't used Rollup before, but since the Scent is not that big and everything is kinda tied together. I don't see a point in using it. I am sure that bundle size could be optimized more and definitely don't include eg. whole lodash, but that's something for later.

Using module bundler is of course win-win situation, but I suppose there are still people that just need bundle ready for use. Having dependencies inside the bundle can simplify things for some people, but other might get conflicts when using at least one of the dependency, so I want to keep those separate.

Eventually I would like to rewrite Scent using ES6 just to keep up with a good stuff and perhaps make this maintainable for more people.
