### ISSUE TITLE
Make better tutorial and setup small demo

### ISSUE THREAD

**Issue by danielkcz** [BlackDice/scent#20]
Current door closing example in README can help to understand basics, but it doesn't highlight well separate parts of framework and how they can be helpful. Also without actually seeing it in action it's somewhat hard to imagine whole functionality.

Tutorial should go from fundamentals and adding more complexity over time. Demo can be hosted on JSFiddle or something similar, although it would need to include whole Scent inline in there as we don't have a way to host it.

**Comment by martikaljuve** [comment]
I agree, having a small demo would be nice to get started with Scent. Do you mean a tutorial repository where every commit builds upon the previous to get a fully working game, or are you thinking of separate example directories for different parts of the framework?

I would think a scent-demo project on github with `gh-pages` would be sufficient. The URL would then be http://blackdice.github.io/scent-demo/ and all the assets would be hosted by GitHub.

**Comment by danielkcz** [comment]
Well for starters I want to expand this door closing piece of code into working demo and describe step by step what's going on in there. I would probably just use CodePen for now and to actually create template there so anybody can experiment with it.

Later on I would like to replicate this using Scent: https://github.com/nckpark/AshJS/tree/master/ashteroidsJS

Any help would be much appreciated if you can create some working examples on your own.
