### ISSUE TITLE
What is purpose of the System?

### ISSUE THREAD

**Issue by danielkcz** [BlackDice/scent#24]
The implementation of the System is very weak attempt to give ability to organize game code. However in the overall it creates only a confusion and doesn't help at all. There is no possibility to remove (or disable) a system once it has been added to the Engine. We cannot organize Systems in any way except controlling order they are added in. System code will be just executed once when `engine.start` is invoked. There is nothing else behind this.

Basically we need to call the Engine methods like `onUpdate`, but these can be registered anywhere as it mostly depends when we call the actual `engine.update`. Also async nature of the System was kinda blind shot. So far we had no need to use that and we kinda ended up creating separate modules for any async code anyway.

Do we need to include the System at all? Wouldn't be better to remove it completely and just leave this open for people to implement however they want instead of confusing them?

There is another derived issue around this - lack of cleanup methods. We can add handler to `onUpdate` or signup for changes in the Node (with `onAdded` & `onRemoved`), but there is no way to actually remove these handlers once they are not needed. This is kinda essential to implementing state machine which usually need to disable code that shouldn't be run anymore.

Lately I am working with ReactJS and I absolutely love the way how the components are organized, nested and updated. Of course the overall API isn't that useful for Scent needs, but I can imagine something like this (forgive me ES6 syntax):

``` js
class AnimationSystem extends Scent.System {
    systemWillStart() {
        // first time setup before first update is run
    }
    systemDidStart() {
        // first time setup after first update has run
    }
    shouldSystemUpdate() {
        // enable/disable system completely based on some state
    }
    systemWillUpdate() {
        // code before actual update 
    }
    update(timestamp) {
        // essentially just engine.onUpdate
    }
    execute() {
        return [
            SparkleSystem,
            ShadowSystem,
        ]
    }
    systemDidUpdate() {
        // code after the update
    }
    systemWillEnd() {
        // cleanup before system is going to be removed
    }
    systemDidEnd() {
        // cleanup after the system has been removed
    }
}
```

All these "lifecycle" methods would be completely optional, but giving great power when needed. However there is kinda a lot of work behind to implement this. Perhaps we can use ReactJS under it since version 0.14 is no longer dependent on DOM anyway. Also possibility to use the `props` and perhaps even the `state` might be useful in configuring these Systems dynamically.

Well it's all just idea and definitely need more thinking and possibly some opinions (@martikaljuve ?).

**Comment by martikaljuve** [comment]
Ah, very interesting! I've used React + Flux (using [Alt.js](http://alt.js.org/)) for the past few months and haven't found it as easy as [Ractive](http://www.ractivejs.org/), but for this case I agree it could work well. 

I presume `engine.addSystem` would still be required to register the systems in the correct order. Would the Systems still get access to the whole engine instance, or are you thinking of encapsulating functions like `onAction` and `getNodeType` in the Systems as well?

Hitagi.js, another recent ECS, also has Systems with overridable functions, but it is quite limited in that you can only subscribe to single components in the update method: https://github.com/RoganMurley/hitagi.js/wiki/System

**Comment by danielkcz** [comment]
Flux is not that good, [Redux](https://github.com/rackt/redux) implementation is much better in my opinion. I don't know Ractive, but there is a bunch of approaches lately building on ideas of React.

I am not sure if `engine.addSystem` is useful that much. It should work like creating tree of components in React. You will have a single entry System and then in a `execute` method you would specify other systems to run in specified order. These can again specify their own subsystems and so on. That would allow to control dynamically what systems are being executed based on some states and in my opinion it should be more clear what is happening where.

Regarding other methods like `getNodeType`, I suppose that you would need engine instance there anyway, so you can use them in there for sure. Additionally there could be a way to specify node types you are interested in and the System would grab them for you and when a system is removed (not returned from the `execute` method) it would do proper cleanup. Same for actions.

Hitagi.js looks very interesting, I will definitely investigate and perhaps get some inspiration there. Thanks!

**Comment by martikaljuve** [comment]
Oh, I didn't realize the `execute` method is similar to React's `render` method, it makes sense now. In that case `engine.addSystem` does seem redundant.

**Comment by danielkcz** [comment]
I am essentially thinking to leave the System as it is in the Scent, but make a separate project with this approach. In that case keeping `addSystem` is necessary to actually add top level system into the mix.

I am curious @martikaljuve, how much would this new approach help you in your project? I suppose that you use something different to organize your code too and you are not going to change it. I am certain that  it would help us for our game, so I am soon going to design this in more detail.

**Comment by martikaljuve** [comment]
My Scent projects have been really simple right now, mostly just 2D sprites or 3D meshes slowly panning across the screen with some touch interactivity. I've managed fine with just top-level systems with no nesting. As soon as I get to create something more game-like, I would find more use for nesting and adding/removing systems.

I've been reading up on Redux now, the documentation is excellent.

**Comment by martikaljuve** [comment]
I've been using React extensively for the last year, so I could help with experimenting with this new approach if you ever feel like it. 

This evening I tried to hack together Scent and React, here's the result: https://github.com/martikaljuve/scent-react-example/tree/master/app

Another approach could be to implement a replacement to `ReactDOM.render` without using the DOM. It might also be interesting to not depend on React, but use JSX with a custom pragma, e.g. `Scent.createSystem` instead of `React.createElement`.

**Comment by danielkcz** [comment]
Hey. It's great that you are still interested in using Scent. Sadly me not so much. We have kinda abandoned our attempt of making game in Javascript for now and working on it with Unreal Engine. Honestly I don't have much of motivation to maintain Scent right now. Would you be perhaps interested in it? I could still provide code review and such.

**Comment by martikaljuve** [comment]
I would be up for it, but I'm not well-versed in CoffeeScript. I've been planning to write something similar using ES6 or possibly TypeScript, but that should probably happen in another project. 

On another note, have you looked at Mozilla's [A-Frame](https://github.com/aframevr/aframe/)? They have an interesting approach of having entities defined in the DOM using Custom Elements.

**Comment by danielkcz** [comment]
Honestly I don't use CoffeeScript anymore for some time now. I regret now that Scent got caught in the time I've been CoffeeScript admirer. So either rewrite this or make it as a new project entirely, it's up to you. I've added you as a collaborator.

I don't know anything about A-Frame and I am not sure how having some state in DOM could be a good thing. How are you going to make a server based logic then? I don't like that idea at all :)
