### ISSUE TITLE
Only first Node.onAdded callback is firing?

### ISSUE THREAD

**Issue by martikaljuve** [BlackDice/scent#5]
E.g. with this:

``` javascript
nStructure.onAdded(function(node) {
   // first callback
});

nStructure.onAdded(function(node) {
   // second callback
});
```

Only the first one gets called.

Looking at [src/node.coffee#L156](https://github.com/BlackDice/scent/blob/f132436b9290b5102ff3df17a3bfff563abceb21/src/node.coffee#L156) and [lib/node.js#L154](https://github.com/BlackDice/scent/blob/f132436b9290b5102ff3df17a3bfff563abceb21/lib/node.js#L154), the onAdded callback list gets cleared after the first one is called. This is probably not as intended? Moving `Lill.clear added` outside the for-loop made it work.

**Comment by danielkcz** [comment]
Thanks ! That seems about right. Some indentation probably slipped away in there :) Same for the removed nodes below. Would you mind fixing it and possibly add tests to address this issue? I am currently swamped.

**Comment by martikaljuve** [comment]
Sure thing, will do it tomorrow! 

By the way, the latest coffee-script `1.9.1` gives a bit different results when compiling *.coffee => *.js with `node bin/build.js`, e.g:

lib/action.js:

``` diff
-  this.data = data;
-  this.meta = meta;
+  this.data = data1;
+  this.meta = meta1;
/../
-  var _ref;
-  return (_ref = this.data) != null ? _ref[prop] : void 0;
+  var ref;
+  return (ref = this.data) != null ? ref[prop] : void 0;
/../
-  var action, data, fn, _i, _len, _ref, _ref1;
+  var action, data, fn, i, len, ref, ref1;
```

lib/system.js:

``` diff
-var symbols, _;
+var _, symbols;
```

etc. I downgraded to 1.8.0 for now.

**Comment by danielkcz** [comment]
Yes, I've noticed that change, but it's mainly internal thing. Only place where you need to worry about it is in function arguments.

```
someFunction = (@arg) ->
    arg is @arg # this is actually false, you have to use @arg always.
```

It shouldn't be an issue for Scent as there is very sparse use of `this`.

**Comment by danielkcz** [comment]
Thanks for the quick commit, Can you please add the same for `onRemoved` ?

**Comment by martikaljuve** [comment]
I think onRemoved is OK? I added a test for it now as well.

**Comment by danielkcz** [comment]
Ah, you are right, it was just my quick eye :) Awesome.
